export const homeObjOne = {
  id: "upload",
  to: "signup",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "당신의 사진을 업로드 하세요",
  headline: "Upload your memory",
  description: "그 때 그 장소의 추억을 간직해보세요",
  buttonLabel: "시작하기",
  imgStart: false,
  img: require("../../images/posting.png"),
  alt: "upload photo",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "posting",
  to: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "방문했던 장소를 지도 위에 포스팅 하세요",
  headline: "Posting your location",
  description: "지도를 펼치면 다녀온 장소를 한 눈에 볼 수 있어요",
  buttonLabel: "더 배워보기",
  imgStart: true,
  img: require("../../images/img02.png"),
  alt: "posting location",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "diary",
  to: "home",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "사진과 함께 다이어리를 작성해보세요",
  headline: "Write a diary",
  description: "추억을 세세하게 기록할 수 있어요",
  buttonLabel: "상단으로 가기",
  imgStart: false,
  img: require("../../images/img03.png"),
  alt: "write a diary",
  dark: true,
  primary: true,
  darkText: false,
};
